### ISSUE TITLE
Tensor error float in 1.Novice 2-neural-networks.ipynb

### ISSUE THREAD

**Issue by benjaminjohansen** [munkai/pytorch-tutorial#1]
Hey,

In section 2. Loss function, the code won't compile and throws the error

```output = net(input)
target = Variable(torch.arange(1, 11))  # a dummy target, for example
criterion = nn.MSELoss()
loss = criterion(output, target)
print(loss)
```

` RuntimeError: Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #2 'target'`

I fixed it by adding this line after target
```output = net(input)
target = Variable(torch.arange(1, 11, dtype=torch.float32))  # a dummy target, for example
target = torch.tensor(target, dtype=torch.float32, requires_grad=True) # convert target to float 32 tensor
criterion = nn.MSELoss()
loss = criterion(output.squeeze(), target)
print(loss)
```

Can you check if it's just my code that won't compile, unless I change target from int to float?

I'm running the script on **Google Colab**.

Cheers!

**Comment by Obeyed** [comment]
Hi Benjamin. When the code was written it worked. However some later update might have broken some expectations?

I'm no longer maintaining this tutorial. Glad you fixed the issue! :+1:
